repos:
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
          - id: black
            language_version: python3
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.2.3
      hooks:
          - id: flake8
            exclude: ^build/*
            additional_dependencies:
                - flake8-builtins
                - flake8-comprehensions
                - flake8-docstrings
                - flake8-tuple
                - flake8-quotes
                - pep8-naming
