"""Expected results for feature_to_rst."""

basic_rst = [
    ".. role:: gherkin-step-keyword\n",
    "\n",
    "Feature: Testing Sphinx Writer\n",
    "==============================\n\n",
    "    Test the ability to write Gherkin data to a SphinxWriter object\n",
    "\n",
    "Background: Some requirements for this test\n",
    "-------------------------------------------\n\n",
    "| - :gherkin-step-keyword:`Given` that this file exists\n",
    "\n",
    "Scenario: Test a Scenario\n",
    "-------------------------\n\n",
    ".. pull-quote::\n\n",
    "    Tagged: quarantined, JIRA-1234\n\n",
    "    A scenario is quicker to write than a outline but less robust.\n",
    "\n",
    "| - :gherkin-step-keyword:`Given` a test feature\n",
    "| - :gherkin-step-keyword:`When` the suite reaches a scenario\n",
    "| - :gherkin-step-keyword:`Then` the file is converted into rST\n",
    "\n",
    "Scenario Outline: Test a Scenario Outline\n",
    "-----------------------------------------\n\n",
    "| - :gherkin-step-keyword:`Given` I put **\\<thing\\>** in a blender\n",
    "| - :gherkin-step-keyword:`When` I turn the blender on\n",
    "| - :gherkin-step-keyword:`Then` it should transform into **\\<other thing\\>**\n",
    "\n",
    "Examples: Fruit\n",
    "~~~~~~~~~~~~~~~\n\n",
    ".. csv-table::\n",
    '    :header: "thing", "other thing"\n',
    "    :quote: “\n\n",
    "    “apple“, “apple sauce“\n",
    "    “banana“, “smoothie“\n",
    "\n",
    "Scenario: Text and Table Scenario\n",
    "---------------------------------\n\n",
    "    Test the additional options for a scenario\n",
    "\n",
    "| - :gherkin-step-keyword:`Given` step text\n",
    "\n",
    "::\n\n",
    "    Lorum ipsum solor sit amet.\n\n",
    "| - :gherkin-step-keyword:`When` the suite reaches a scenario table\n",
    "\n",
    "    .. csv-table::\n",
    '        :header: "name", "department"\n',
    "        :quote: “\n\n",
    "        “Barry“, “Beer Cans“\n",
    "        “Pudey“, “Silly Walks“\n",
    "        “Two-Lumps“, “Silly Walks“\n",
    "\n",
    "| - :gherkin-step-keyword:`Then` the file is converted into rST\n",
    "\n",
    "Scenario: Normal scenarios with add on steps (And, But) have those add on steps indented\n",
    "----------------------------------------------------------------------------------------\n\n",
    "| - :gherkin-step-keyword:`Given` something not indented\n",
    "|  :gherkin-step-keyword:`And` something else that IS indented\n",
    "| - :gherkin-step-keyword:`When` something not indented happens\n",
    "| - :gherkin-step-keyword:`Then` something not indented happened\n",
    "|  :gherkin-step-keyword:`And` something indented also happened\n",
    "|  :gherkin-step-keyword:`And` another indented thing happened\n",
    "\n",
    "Scenario: Indentation is ignored when any step in the scenario has text or a table\n",
    "----------------------------------------------------------------------------------\n\n",
    "| - :gherkin-step-keyword:`Given` a step with some text\n",
    "\n",
    "::\n\n",
    "    Here be that said text!\n\n",
    "| - :gherkin-step-keyword:`And` an And step with some text too\n",
    "\n",
    "::\n\n",
    "    Hello again!\n\n",
    "| - :gherkin-step-keyword:`And` how about a table in there too\n",
    "\n",
    "    .. csv-table::\n",
    '        :header: "position", "name"\n',
    "        :quote: “\n\n",
    "        “first“, “Who“\n",
    "        “second“, “What“\n",
    "        “third“, “I don't know“\n",
    "\n",
    "| - :gherkin-step-keyword:`When` the fantasy has ended\n",
    "| - :gherkin-step-keyword:`And` all the children are gone\n",
    "| - :gherkin-step-keyword:`Then` something deep inside me\n",
    "\n",
    "::\n\n",
    "    Helps me to carry on\n\n",
    "| - :gherkin-step-keyword:`And` Encarnaciooooon\n",
    "| - :gherkin-step-keyword:`And` doodle-doodle-doodle-doo\n",
    "\n",
]

basic_rst_with_integrated_background = [
    ".. role:: gherkin-step-keyword\n",
    "\n",
    "Feature: Testing Sphinx Writer\n",
    "==============================\n\n",
    "    Test the ability to write Gherkin data to a SphinxWriter object\n",
    "\n",
    "Scenario: Test a Scenario\n",
    "-------------------------\n\n",
    ".. pull-quote::\n\n",
    "    Tagged: quarantined, JIRA-1234\n\n",
    "    A scenario is quicker to write than a outline but less robust.\n",
    "\n",
    "| - :gherkin-step-keyword:`Given` that this file exists\n",
    "| - :gherkin-step-keyword:`Given` a test feature\n",
    "| - :gherkin-step-keyword:`When` the suite reaches a scenario\n",
    "| - :gherkin-step-keyword:`Then` the file is converted into rST\n",
    "\n",
    "Scenario Outline: Test a Scenario Outline\n",
    "-----------------------------------------\n\n",
    "| - :gherkin-step-keyword:`Given` that this file exists\n",
    "| - :gherkin-step-keyword:`Given` I put **\\<thing\\>** in a blender\n",
    "| - :gherkin-step-keyword:`When` I turn the blender on\n",
    "| - :gherkin-step-keyword:`Then` it should transform into **\\<other thing\\>**\n",
    "\n",
    "Examples: Fruit\n",
    "~~~~~~~~~~~~~~~\n\n",
    ".. csv-table::\n",
    '    :header: "thing", "other thing"\n',
    "    :quote: “\n\n",
    "    “apple“, “apple sauce“\n",
    "    “banana“, “smoothie“\n",
    "\n",
    "Scenario: Text and Table Scenario\n",
    "---------------------------------\n\n",
    "    Test the additional options for a scenario\n",
    "\n",
    "| - :gherkin-step-keyword:`Given` that this file exists\n",
    "| - :gherkin-step-keyword:`Given` step text\n",
    "\n",
    "::\n\n",
    "    Lorum ipsum solor sit amet.\n\n",
    "| - :gherkin-step-keyword:`When` the suite reaches a scenario table\n",
    "\n",
    "    .. csv-table::\n",
    '        :header: "name", "department"\n',
    "        :quote: “\n\n",
    "        “Barry“, “Beer Cans“\n",
    "        “Pudey“, “Silly Walks“\n",
    "        “Two-Lumps“, “Silly Walks“\n",
    "\n",
    "| - :gherkin-step-keyword:`Then` the file is converted into rST\n",
    "\n",
    "Scenario: Normal scenarios with add on steps (And, But) have those add on steps indented\n",
    "----------------------------------------------------------------------------------------\n\n",
    "| - :gherkin-step-keyword:`Given` that this file exists\n",
    "| - :gherkin-step-keyword:`Given` something not indented\n",
    "|  :gherkin-step-keyword:`And` something else that IS indented\n",
    "| - :gherkin-step-keyword:`When` something not indented happens\n",
    "| - :gherkin-step-keyword:`Then` something not indented happened\n",
    "|  :gherkin-step-keyword:`And` something indented also happened\n",
    "|  :gherkin-step-keyword:`And` another indented thing happened\n",
    "\n",
    "Scenario: Indentation is ignored when any step in the scenario has text or a table\n",
    "----------------------------------------------------------------------------------\n\n",
    "| - :gherkin-step-keyword:`Given` that this file exists\n",
    "| - :gherkin-step-keyword:`Given` a step with some text\n",
    "\n",
    "::\n\n",
    "    Here be that said text!\n\n",
    "| - :gherkin-step-keyword:`And` an And step with some text too\n",
    "\n",
    "::\n\n",
    "    Hello again!\n\n",
    "| - :gherkin-step-keyword:`And` how about a table in there too\n",
    "\n",
    "    .. csv-table::\n",
    '        :header: "position", "name"\n',
    "        :quote: “\n\n",
    "        “first“, “Who“\n",
    "        “second“, “What“\n",
    "        “third“, “I don't know“\n",
    "\n",
    "| - :gherkin-step-keyword:`When` the fantasy has ended\n",
    "| - :gherkin-step-keyword:`And` all the children are gone\n",
    "| - :gherkin-step-keyword:`Then` something deep inside me\n",
    "\n",
    "::\n\n",
    "    Helps me to carry on\n\n",
    "| - :gherkin-step-keyword:`And` Encarnaciooooon\n",
    "| - :gherkin-step-keyword:`And` doodle-doodle-doodle-doo\n",
    "\n",
]

basic_rst_unique_integrated_background_step_format = [
    ".. role:: gherkin-step-keyword\n",
    "\n",
    "Feature: Testing Sphinx Writer\n",
    "==============================\n\n",
    "    Test the ability to write Gherkin data to a SphinxWriter object\n",
    "\n",
    "Scenario: Test a Scenario\n",
    "-------------------------\n\n",
    ".. pull-quote::\n\n",
    "    Tagged: quarantined, JIRA-1234\n\n",
    "    A scenario is quicker to write than a outline but less robust.\n",
    "\n",
    "| - :gherkin-step-keyword:`Given` that this file exists *(Background)*\n",
    "| - :gherkin-step-keyword:`Given` a test feature\n",
    "| - :gherkin-step-keyword:`When` the suite reaches a scenario\n",
    "| - :gherkin-step-keyword:`Then` the file is converted into rST\n",
    "\n",
    "Scenario Outline: Test a Scenario Outline\n",
    "-----------------------------------------\n\n",
    "| - :gherkin-step-keyword:`Given` that this file exists *(Background)*\n",
    "| - :gherkin-step-keyword:`Given` I put **\\<thing\\>** in a blender\n",
    "| - :gherkin-step-keyword:`When` I turn the blender on\n",
    "| - :gherkin-step-keyword:`Then` it should transform into **\\<other thing\\>**\n",
    "\n",
    "Examples: Fruit\n",
    "~~~~~~~~~~~~~~~\n\n",
    ".. csv-table::\n",
    '    :header: "thing", "other thing"\n',
    "    :quote: “\n\n",
    "    “apple“, “apple sauce“\n",
    "    “banana“, “smoothie“\n",
    "\n",
    "Scenario: Text and Table Scenario\n",
    "---------------------------------\n\n",
    "    Test the additional options for a scenario\n",
    "\n",
    "| - :gherkin-step-keyword:`Given` that this file exists *(Background)*\n",
    "| - :gherkin-step-keyword:`Given` step text\n",
    "\n",
    "::\n\n",
    "    Lorum ipsum solor sit amet.\n\n",
    "| - :gherkin-step-keyword:`When` the suite reaches a scenario table\n",
    "\n",
    "    .. csv-table::\n",
    '        :header: "name", "department"\n',
    "        :quote: “\n\n",
    "        “Barry“, “Beer Cans“\n",
    "        “Pudey“, “Silly Walks“\n",
    "        “Two-Lumps“, “Silly Walks“\n",
    "\n",
    "| - :gherkin-step-keyword:`Then` the file is converted into rST\n",
    "\n",
    "Scenario: Normal scenarios with add on steps (And, But) have those add on steps indented\n",
    "----------------------------------------------------------------------------------------\n\n",
    "| - :gherkin-step-keyword:`Given` that this file exists *(Background)*\n",
    "| - :gherkin-step-keyword:`Given` something not indented\n",
    "|  :gherkin-step-keyword:`And` something else that IS indented\n",
    "| - :gherkin-step-keyword:`When` something not indented happens\n",
    "| - :gherkin-step-keyword:`Then` something not indented happened\n",
    "|  :gherkin-step-keyword:`And` something indented also happened\n",
    "|  :gherkin-step-keyword:`And` another indented thing happened\n",
    "\n",
    "Scenario: Indentation is ignored when any step in the scenario has text or a table\n",
    "----------------------------------------------------------------------------------\n\n",
    "| - :gherkin-step-keyword:`Given` that this file exists *(Background)*\n",
    "| - :gherkin-step-keyword:`Given` a step with some text\n",
    "\n",
    "::\n\n",
    "    Here be that said text!\n\n",
    "| - :gherkin-step-keyword:`And` an And step with some text too\n",
    "\n",
    "::\n\n",
    "    Hello again!\n\n",
    "| - :gherkin-step-keyword:`And` how about a table in there too\n",
    "\n",
    "    .. csv-table::\n",
    '        :header: "position", "name"\n',
    "        :quote: “\n\n",
    "        “first“, “Who“\n",
    "        “second“, “What“\n",
    "        “third“, “I don't know“\n",
    "\n",
    "| - :gherkin-step-keyword:`When` the fantasy has ended\n",
    "| - :gherkin-step-keyword:`And` all the children are gone\n",
    "| - :gherkin-step-keyword:`Then` something deep inside me\n",
    "\n",
    "::\n\n",
    "    Helps me to carry on\n\n",
    "| - :gherkin-step-keyword:`And` Encarnaciooooon\n",
    "| - :gherkin-step-keyword:`And` doodle-doodle-doodle-doo\n",
    "\n",
]

tags_rst = [
    ".. role:: gherkin-step-keyword\n",
    "\n",
    "Feature: Testing Sphinx Writer\n",
    "==============================\n\n",
    "    Test the ability to write Gherkin data to a SphinxWriter object\n",
    "\n",
    "Background: Some requirements for this test\n",
    "-------------------------------------------\n\n",
    "| - :gherkin-step-keyword:`Given` that this file exists\n",
    "\n",
    "Scenario: Test a Scenario\n",
    "-------------------------\n\n",
    ".. pull-quote::\n\n",
    "    Tagged: api (Inherited from Feature: positive )\n\n",
    "    A scenario is quicker to write than a outline but less robust.\n",
    "\n",
    "| - :gherkin-step-keyword:`Given` a test feature\n",
    "| - :gherkin-step-keyword:`When` the suite reaches a scenario\n",
    "| - :gherkin-step-keyword:`Then` the file is converted into rST\n",
    "\n",
]
