"""Expected results for feature_to_rst."""

basic_rst = [
    "Feature: Testing Sphinx Writer\n",
    "==============================\n\n",
    "    Test the ability to write Gherkin data to a SphinxWriter object\n",
    "\n",
    "Background: Some requirements for this test\n",
    "-------------------------------------------\n\n",
    "- Given that this file exists\n",
    "\n",
    "Scenario: Test a Scenario\n",
    "-------------------------\n\n",
    ".. pull-quote::\n\n",
    "    Tagged: quarantined, JIRA-1234\n\n",
    "    A scenario is quicker to write than a outline but less robust.\n",
    "\n",
    "- Given a test feature\n",
    "- When the suite reaches a scenario\n",
    "- Then the file is converted into rST\n",
    "\n",
    "Scenario Outline: Test a Scenario Outline\n",
    "-----------------------------------------\n\n",
    "- Given I put **\\<thing\\>** in a blender\n",
    "- When I turn the blender on\n",
    "- Then it should transform into **\\<other thing\\>**\n",
    "\n",
    "Examples: Fruit\n",
    "~~~~~~~~~~~~~~~\n\n",
    ".. csv-table::\n",
    '    :header: "thing", "other thing"\n',
    "    :quote: “\n\n",
    "    “apple“, “apple sauce“\n",
    "    “banana“, “smoothie“\n",
    "\n",
    "Scenario: Text and Table Scenario\n",
    "---------------------------------\n\n",
    "    Test the additional options for a scenario\n",
    "\n",
    "- Given step text\n",
    "\n",
    "::\n\n",
    "    Lorum ipsum solor sit amet.\n\n",
    "- When the suite reaches a scenario table\n",
    "\n",
    "    .. csv-table::\n",
    '        :header: "name", "department"\n',
    "        :quote: “\n\n",
    "        “Barry“, “Beer Cans“\n",
    "        “Pudey“, “Silly Walks“\n",
    "        “Two-Lumps“, “Silly Walks“\n",
    "- Then the file is converted into rST\n",
    "\n",
]

tags_rst = [
    "Feature: Testing Sphinx Writer\n",
    "==============================\n\n",
    "    Test the ability to write Gherkin data to a SphinxWriter object\n",
    "\n",
    "Background: Some requirements for this test\n",
    "-------------------------------------------\n\n",
    "- Given that this file exists\n",
    "\n",
    "Scenario: Test a Scenario\n",
    "-------------------------\n\n",
    ".. pull-quote::\n\n",
    "    Tagged: api (Inherited from Feature: positive )\n\n",
    "    A scenario is quicker to write than a outline but less robust.\n",
    "\n",
    "- Given a test feature\n",
    "- When the suite reaches a scenario\n",
    "- Then the file is converted into rST\n",
    "\n",
]
